### ISSUE TITLE
Deleting closed issues from the DCAT document

### ISSUE THREAD

**Issue by riccardoAlbertoni** [w3c/dx-dcat#352]
I have noticed some closed issues are still included in the DCAT document, though they have been closed. (i.e., w3c/dx-dcat#478, w3c/dx-dcat#493, w3c/dx-dcat#371, w3c/dx-dcat#448, w3c/dx-dcat#435) 

shall we remove them?

**Comment by davebrowning** [comment]
Good idea.  But we need to be check that they are recorded in [Appendix E](https://w3c.github.io/dxwg/dcat/#changes) appropriately.  So I'd expect w3c/dx-dcat#478 and w3c/dx-dcat#493 to be noted in Appendix E since they are differences to the 2014 spec driven by requirements.  w3c/dx-dcat#371 is an issue in one of our WDs so references to it can just be deleted now it has been resolved.  w3c/dx-dcat#448 looks a bit more complicated (reading on small UI device and its a long thread - would have to check what DCAT 2014 actually said against what we say now)

**Comment by riccardoAlbertoni** [comment]
I am going  to prepare a new pull for 
- deleting  w3c/dx-dcat#371  

and completing the existing pull  
- adding  w3c/dx-dcat#478 and w3c/dx-dcat#493 in appendix E,

I leave for a more informed contributor the w3c/dx-dcat#448 ;)

**Comment by riccardoAlbertoni** [comment]
@davebrowning:
as far as I am concerned the pulls w3c/dxwg#634 and w3c/dxwg#635 tidy up the closed issues w3c/dx-dcat#371, w3c/dx-dcat#478, w3c/dx-dcat#493  and can be merged.
Cheers

**Comment by davebrowning** [comment]
Thanks @riccardoAlbertoni - that's great, both merged.  Suggest we leave this open till we have a chance to look at w3c/dx-dcat#448

**Comment by davebrowning** [comment]
w3c/dx-dcat#448 now addressed by w3c/dxwg#645, and merged
